// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIIsBVcmIdadApGUEVPsI4vjTlSj62UKI',
    appId: '1:684009601734:web:2353c7996c4bcbd92ab5c7',
    messagingSenderId: '684009601734',
    projectId: 'social-media-app-79e3a',
    authDomain: 'social-media-app-79e3a.firebaseapp.com',
    storageBucket: 'social-media-app-79e3a.firebasestorage.app',
    measurementId: 'G-SSD2499YMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXoTQCneXbKGbDcIKDPKIyjTlMAzl4MY',
    appId: '1:684009601734:android:b5a0065ecebb69672ab5c7',
    messagingSenderId: '684009601734',
    projectId: 'social-media-app-79e3a',
    storageBucket: 'social-media-app-79e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91QpK932UeWXDipygaBN9JYg6W0Qkz30',
    appId: '1:684009601734:ios:ecd14e02622901192ab5c7',
    messagingSenderId: '684009601734',
    projectId: 'social-media-app-79e3a',
    storageBucket: 'social-media-app-79e3a.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC91QpK932UeWXDipygaBN9JYg6W0Qkz30',
    appId: '1:684009601734:ios:ecd14e02622901192ab5c7',
    messagingSenderId: '684009601734',
    projectId: 'social-media-app-79e3a',
    storageBucket: 'social-media-app-79e3a.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIIsBVcmIdadApGUEVPsI4vjTlSj62UKI',
    appId: '1:684009601734:web:2b012bc2fc5affec2ab5c7',
    messagingSenderId: '684009601734',
    projectId: 'social-media-app-79e3a',
    authDomain: 'social-media-app-79e3a.firebaseapp.com',
    storageBucket: 'social-media-app-79e3a.firebasestorage.app',
    measurementId: 'G-VKL5G6R2GM',
  );
}
